sprint five project work
YuriyZanin/go-first-floor-sprint-five pull request #1
Opened 2023-11-18 13:04 UTC by YuriyZanin

Sprint 5

2023-11-23 14:14 UTC, just-musha requested changes
Важный комментарий добавила. Нужно поправить TrainingInfo для Swimming, чтобы в ней вызывался корректный метод расчета средней скорости.

2023-11-23 14:14 UTC, just-musha commented on main.go
> +	return s.Training.TrainingInfo()
Вот здесь важнsый момент: в running/walking у нас скорость расчитывается по "базовой" формуле, которая есть в Training. В случае с плаванием, скорость вычисляется в конкретной реализации. Здесь тебе нужно завести структуру InfoMessage и там явно вызвать метод s.meanSpeed()  для Swimming, и вернуть эту структуру

2023-11-23 14:30 UTC, just-musha requested changes
Привет!

Предлагаю обязательно поправить вызов meanSpeed и добавить проверку Duration на 0. И конечно же запустить go fmt для красоты.

В остальном все хорошо, так держать. Жду правки и принимаю работу.

2023-11-23 14:30 UTC, just-musha commented on main.go
> +	Duration time.Duration 			// продолжительность тренировки
Тут можно go fmt запустить, чтоб отступы выровнять

2023-11-23 14:30 UTC, just-musha commented on main.go
> +	return 	t.distance() / t.Duration.Hours()
Что будет если Duration = 0 ? Предлагаю обработать этот случай, например добавить проверку и возвращать из функции 0

2023-11-23 14:30 UTC, just-musha commented on main.go
> -	...
Аналогично нужна проверка на Duration = 0

2023-11-23 14:30 UTC, just-musha commented on main.go
> +	return ((CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed()*KmHInMsec, 2) / (w.Height/CmInM)) * CaloriesSpeedHeightMultiplier * w.Weight) * w.Duration.Hours() * MinInHours)
Здесь можно разбить длинную строку с помощью переносов строки - для лучшей читаемости

2023-11-23 16:25 UTC, YuriyZanin commented on main.go
> +	return s.Training.TrainingInfo()
Сделано

2023-11-23 16:27 UTC, YuriyZanin commented on main.go
> +	return 	t.distance() / t.Duration.Hours()
добавил проверку на 0

2023-11-23 16:28 UTC, YuriyZanin commented on main.go
> -	...
добавил проверку

2023-11-23 16:34 UTC, YuriyZanin commented on main.go
> +	return ((CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed()*KmHInMsec, 2) / (w.Height/CmInM)) * CaloriesSpeedHeightMultiplier * w.Weight) * w.Duration.Hours() * MinInHours)
разбил на две строки

2023-11-23 16:34 UTC, YuriyZanin commented on main.go
> +	Duration time.Duration 			// продолжительность тренировки
отступы поправил

2023-11-23 20:58 UTC, just-musha approved these changes
Спасибо за быстрые правки.

Оставила ещй пару коментариев, которые проглядела сразу. Они в целом не крит, если есть время и желание - докинь изменения в веточку.
Работа принята.

2023-11-23 20:58 UTC, just-musha commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow(w.meanSpeed()*KmHInMsec, 2)/(w.Height/CmInM))*
Проглядели мы ещё одно деление на 0. Для Height тоже бы добавить проверку.

2023-11-23 20:58 UTC, just-musha commented on main.go
> +		s.Calories(),
Ещё подсвечу не большой момент - сорри только сейчас заметила - вот здесь у тебя сразу записывается правильное значение Calories. По заданию предполагается что это будет сделано в функции ReadData.
Это вообще не критично - но возможно дальше по курсу задание будет развиваться, и мб на что-то повлияет. Предлагаю сразу поправить или просто держать это в уме.

2023-11-24 05:50 UTC, YuriyZanin commented on main.go
> +	return ((CaloriesWeightMultiplier*w.Weight + (math.Pow(w.meanSpeed()*KmHInMsec, 2)/(w.Height/CmInM))*
добавил проверку на 0

2023-11-24 05:55 UTC, YuriyZanin commented on main.go
> +		s.Calories(),
убрал вызов метода, инициализировал нулевым значением

2023-11-24 06:04 UTC, merged